### ISSUE TITLE
请教一下关于同步的几个问题

### ISSUE THREAD

**Issue by shenweiyan** [vannvan/knowledge-garden#11]
好不容易能在这里看到一个 GitHub 同步语雀的案例，感谢作者的开源，同时想请问一下作者老哥：

1. 我看到好像只需要设置`YUQUE_USERNAME`和`YUQUE_PASSWORD`，就可以把这个定时任务跑起来了？
2. 这个任务是可以指定语雀的某个知识库进行同步吗？我好像没有看到在哪里可以设置？
3. 如果我也想要一个类似的 Garden，Fork 本仓库后需要做哪些调整？

最后，感谢作者的这个知识库，终于能为个人的语雀同步和备份增加了另外一种可能 >.<

**Comment by vannvan** [comment]
`yuque-tools`是可以将语雀的所有知识库数据爬下来的，通过[这个脚本](https://github.com/vannvan/knowledge-garden/blob/master/scripts/sync-yuque-doc-task.ts)可以看到。目前其实只同步了我的 技术迭代这个知识库的技术月报的目录，对应的yuque-tools的完整执行脚本其实是：
> ytools pull userName password 技术迭代/技术月报 skip lb

更多用法见[导出示例](https://github.com/vannvan/yuque-tools#%E5%AF%BC%E5%87%BA%E7%A4%BA%E4%BE%8B)

上面是主要逻辑，这个步骤主要是`github action`完成的，可以看到会先下载到当前项目的`docs`目录，然后再移动的目标目录(因为目前主要是实验，这个脚本有点复杂)，其实等ytools下载完文档之后，关键步骤就是:
```js
start() {
  // 省略其它
    child.on('close', (code) => {
      console.log('Finished ytool task code ' + code)
      this.handleDocument()
    })
  }

  async handleDocument() {
    console.log('开始处理文件程序')
   // 这个目录是语雀知识库的目录
    const sourceDir = path.resolve('docs/技术迭代/技术月报')
  // 目标目录是本仓库的目录
    const targetDir = path.resolve('Iteration/技术月刊')
  // 覆盖拷贝
    cpSync(sourceDir, targetDir, { recursive: true })
}

```

然后最关键的部分其实就是在"remote"下载完提交刚才的操作了，这里主要是以下方式，通过`ad-m/github-push-action@master`来完成提交 
https://github.com/vannvan/knowledge-garden/blob/master/.github/workflows/aync-yuque-doc.yml
```yaml
 run: |
          git config --global user.email 862670198@qq.com
          git config --global user.name vannvan
          git add .
          git commit -m "同步语雀文档:`date`"
          git pull --rebase

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

```

`github action` 任务里涉及到两个比较重要的东西

1. `GITHUB_TOKEN`  这个通过 Setting -> Secrets and variables -> Actions -> 选择右上角 New repository secret 去生成一个就可以
2. `secrets.YUQUE_USERNAME` 和 `secrets.YUQUE_PASSWORD` 见以下截图
<img width="1102" alt="image" src="https://github.com/vannvan/knowledge-garden/assets/43501134/408a30f3-b125-4b99-b090-eda37ef03470">


另外还有一个很重要的，就是 要把项目的权限调整一下，否则`ad-m/github-push-action@master`它就没有权限帮你完成提交
 settings -> actions -> Genaral -> Workflow permissions  
 
<img width="949" alt="image" src="https://github.com/vannvan/knowledge-garden/assets/43501134/94076234-cc9f-480f-99e8-7f5ca9468152">
以上是将语雀知识库同步到github的完整步骤，这个不算是最佳实践所以没必要fork哈哈哈
