### ISSUE TITLE
css渐变

### ISSUE THREAD

**Issue by vannvan** [vannvan/knowledge-garden#3]
```css
.stripe-bg{
  padding: .5em;
  line-height: 1.5em;
  background: beige;
  background-size: auto 3em;
  background-origin: content-box;
  background-image: linear-gradient(rgba(0,0,0,.2) 50%, transparent 0);
}
```
